<a href="https://colab.research.google.com/github/VIVEKLOYA1809/PROJECT-1/blob/main/data%20analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
dataset=pd.read_excel("Train_data.xlsx",header=None)

In [4]:
dataset_North=dataset.iloc[1:234,3:]
dataset_North=dataset_North.T
dataset_North.columns=dataset.iloc[1:234,2].values
dataset_North.index=dataset.iloc[0,3:].values

In [5]:
outliers={}
def detect_outliers(data):
    mean=np.mean(data)
    std=np.std(data)
    for i in data:
        z_score=(i-mean)/std
        if (z_score>1.9) or (z_score<-1.5) :
            outliers.update({data.index(i):i})
    return outliers

In [6]:
def moving_average(data,i):

    # for i in len(data):

    if(i == 0):
        avg = (data[i]+data[i+1]+data[i+2] ) / 3.0

    elif(i == len(data)-1):
        avg = (data[i-2]+data[i-1]+data[i] ) / 3.0

    else:
        avg = (data[i-1] + data[i] + data[i+1]) / 3.0
    
    return avg

In [7]:
dataset_North_without_outliers=dataset_North.copy()
dataset_North_without_outliers=dataset_North_without_outliers.astype(float)

In [9]:
out_North={}
for i in range(dataset_North.shape[1]):
    outliers={}
    out_North.update({dataset_North.columns[i]:detect_outliers(list(dataset_North.iloc[:,i].values))})
out_North
for items,value in out_North.items():
    for i,j in value.items():
        dataset_North_without_outliers[items][i]=round(moving_average(dataset_North[items],i))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  


In [10]:
def MAPE(Y_actual,Y_pred):
    mape = np.abs((Y_actual - Y_pred)/Y_actual)
    return mape

In [69]:
w=[]
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
for i in range(20):
  stepwise_fit=auto_arima(dataset_North_without_outliers.iloc[:37,i].values,trace=True)
  a=int(input("first"))
  b=int(input("second"))
  c=int(input("third"))
  model=ARIMA(dataset_North_without_outliers.iloc[:37,0].values,order=(a,b,c))
  model=model.fit()
  Y_pred=model.predict(start=37,end=37,type='levels')
  Y_actual=dataset_North_without_outliers.iloc[37,0]
  w.append(MAPE(Y_pred,Y_actual))


Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=237.180, Time=0.24 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=233.704, Time=0.02 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=232.314, Time=0.05 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept   : AIC=232.983, Time=0.03 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=296.576, Time=0.01 sec
 ARIMA(2,0,0)(0,0,0)[0] intercept   : AIC=234.227, Time=0.06 sec
 ARIMA(1,0,1)(0,0,0)[0] intercept   : AIC=234.243, Time=0.08 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=235.285, Time=0.17 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=243.400, Time=0.01 sec

Best model:  ARIMA(1,0,0)(0,0,0)[0] intercept
Total fit time: 0.669 seconds
first1
second0
third0
Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=349.674, Time=0.26 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=365.525, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=356.941, Time=0.05 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept  

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'


Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=504.326, Time=0.22 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=501.873, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=501.744, Time=0.02 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept   : AIC=501.931, Time=0.06 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=525.974, Time=0.01 sec
 ARIMA(2,0,0)(0,0,0)[0] intercept   : AIC=503.723, Time=0.09 sec
 ARIMA(1,0,1)(0,0,0)[0] intercept   : AIC=503.852, Time=0.03 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=505.635, Time=0.04 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=509.749, Time=0.02 sec

Best model:  ARIMA(1,0,0)(0,0,0)[0] intercept
Total fit time: 0.492 seconds
first1
second0
third0
Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=770.570, Time=0.06 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=766.660, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=764.825, Time=0.02 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept  

In [71]:
np.mean(w)


0.16552307755955417

In [72]:
for i in range(20,50):
  stepwise_fit=auto_arima(dataset_North_without_outliers.iloc[:37,i].values,trace=True)
  a=int(input("first"))
  b=int(input("second"))
  c=int(input("third"))
  model=ARIMA(dataset_North_without_outliers.iloc[:37,0].values,order=(a,b,c))
  model=model.fit()
  Y_pred=model.predict(start=37,end=37,type='levels')
  Y_actual=dataset_North_without_outliers.iloc[37,0]
  w.append(MAPE(Y_pred,Y_actual))

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=343.874, Time=0.34 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=345.168, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=345.113, Time=0.07 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=344.292, Time=0.05 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=343.914, Time=0.01 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=347.285, Time=0.16 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=347.212, Time=0.12 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=337.623, Time=0.28 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=339.443, Time=0.19 sec
 ARIMA(4,1,2)(0,0,0)[0] intercept   : AIC=334.885, Time=0.42 sec
 ARIMA(4,1,1)(0,0,0)[0] intercept   : AIC=339.989, Time=0.26 sec
 ARIMA(5,1,2)(0,0,0)[0] intercept   : AIC=336.036, Time=0.45 sec
 ARIMA(4,1,3)(0,0,0)[0] intercept   : AIC=338.217, Time=0.49 sec
 ARIMA(3,1,3)(0,0,0)[0] intercept   : AIC=337.712, Time=0.34 sec
 ARIMA(5,1,1)(0,0,0)[0] intercept   : AIC=334.9

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'


Performing stepwise search to minimize aic
 ARIMA(2,0,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.29 sec
 ARIMA(0,0,0)(0,0,0)[0] intercept   : AIC=490.456, Time=0.01 sec
 ARIMA(1,0,0)(0,0,0)[0] intercept   : AIC=483.191, Time=0.07 sec
 ARIMA(0,0,1)(0,0,0)[0] intercept   : AIC=485.184, Time=0.05 sec
 ARIMA(0,0,0)(0,0,0)[0]             : AIC=512.956, Time=0.01 sec
 ARIMA(2,0,0)(0,0,0)[0] intercept   : AIC=485.128, Time=0.12 sec
 ARIMA(1,0,1)(0,0,0)[0] intercept   : AIC=485.124, Time=0.14 sec
 ARIMA(2,0,1)(0,0,0)[0] intercept   : AIC=487.129, Time=0.11 sec
 ARIMA(1,0,0)(0,0,0)[0]             : AIC=487.157, Time=0.03 sec

Best model:  ARIMA(1,0,0)(0,0,0)[0] intercept
Total fit time: 0.830 seconds
first1
second0
third0
Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.29 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=364.512, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=365.397, Time=0.04 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=3

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'


Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=347.721, Time=0.23 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=365.983, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=367.779, Time=0.04 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=359.362, Time=0.04 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=363.983, Time=0.01 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.17 sec
 ARIMA(2,1,1)(0,0,0)[0] intercept   : AIC=348.194, Time=0.16 sec
 ARIMA(3,1,2)(0,0,0)[0] intercept   : AIC=inf, Time=0.38 sec
 ARIMA(2,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=0.36 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=0.14 sec
 ARIMA(1,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=0.13 sec
 ARIMA(3,1,1)(0,0,0)[0] intercept   : AIC=349.027, Time=0.23 sec
 ARIMA(3,1,3)(0,0,0)[0] intercept   : AIC=inf, Time=0.45 sec
 ARIMA(2,1,2)(0,0,0)[0]             : AIC=346.086, Time=0.16 sec
 ARIMA(1,1,2)(0,0,0)[0]             : AIC=inf, Time=0.07 sec
 ARIMA(2,1

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'


Performing stepwise search to minimize aic
 ARIMA(2,1,2)(0,0,0)[0] intercept   : AIC=393.575, Time=0.22 sec
 ARIMA(0,1,0)(0,0,0)[0] intercept   : AIC=395.171, Time=0.01 sec
 ARIMA(1,1,0)(0,0,0)[0] intercept   : AIC=393.381, Time=0.05 sec
 ARIMA(0,1,1)(0,0,0)[0] intercept   : AIC=389.205, Time=0.06 sec
 ARIMA(0,1,0)(0,0,0)[0]             : AIC=393.180, Time=0.01 sec
 ARIMA(1,1,1)(0,0,0)[0] intercept   : AIC=inf, Time=0.19 sec
 ARIMA(0,1,2)(0,0,0)[0] intercept   : AIC=390.457, Time=0.10 sec
 ARIMA(1,1,2)(0,0,0)[0] intercept   : AIC=391.861, Time=0.13 sec
 ARIMA(0,1,1)(0,0,0)[0]             : AIC=387.675, Time=0.03 sec
 ARIMA(1,1,1)(0,0,0)[0]             : AIC=389.486, Time=0.05 sec
 ARIMA(0,1,2)(0,0,0)[0]             : AIC=389.292, Time=0.05 sec
 ARIMA(1,1,0)(0,0,0)[0]             : AIC=391.452, Time=0.02 sec
 ARIMA(1,1,2)(0,0,0)[0]             : AIC=390.488, Time=0.08 sec

Best model:  ARIMA(0,1,1)(0,0,0)[0]          
Total fit time: 1.028 seconds
first0
second1
third1
Performing stepwi

In [73]:
np.mean(w)


0.1965861909007861

In [74]:
w

[array([0.12889056]),
 array([0.0425795]),
 array([0.01834906]),
 array([0.12889056]),
 array([0.12889056]),
 array([0.12889056]),
 array([0.12889056]),
 array([0.01834906]),
 array([0.12889056]),
 array([0.12141872]),
 array([0.24951165]),
 array([0.12889056]),
 array([0.12889056]),
 array([0.5]),
 array([0.5]),
 array([0.12889056]),
 array([0.01834906]),
 array([0.12889056]),
 array([0.30082328]),
 array([0.2521756]),
 array([0.29834853]),
 array([0.12141872]),
 array([0.12141872]),
 array([0.23083513]),
 array([0.12889056]),
 array([0.5]),
 array([0.5]),
 array([0.5]),
 array([0.12141872]),
 array([0.12889056]),
 array([0.12141872]),
 array([0.27518408]),
 array([0.09569485]),
 array([0.12141872]),
 array([0.12889056]),
 array([0.5]),
 array([0.01834906]),
 array([0.09586107]),
 array([0.01834906]),
 array([0.5]),
 array([0.23083513]),
 array([0.2521756]),
 array([0.23083513]),
 array([0.12141872]),
 array([0.2521756]),
 array([0.12889056]),
 array([0.01834906]),
 array([0.12889056]